# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
# https://symfony.com/doc/3.4/reference/configuration/security.html#reference-security-firewall-form-login
security:
    encoders:
        # BCrypt encoder
        Ood\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    #
    providers:
        user_db:
            entity:
                class: OodUserBundle:User
                ## Use a specific UserRepository::loadUserByUsername()
                # property: username
                # name of a non-default entity manager
                manager_name: ~
    #
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: user_db
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                # the user is redirected here when they need to log in
                login_path: /login
                # submit the login form here
                check_path: /login
                # field names for the username and password fields
                username_parameter: _username
                password_parameter: _password
                # csrf token options
                csrf_parameter:       _crsf_token
                csrf_token_id:        authenticate
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /
                invalidate_session: true
            anonymous: ~
    #
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #
    role_hierarchy:
        ROLE_AUTHOR: [ROLE_USER]
        ROLE_BLOGGER: [ROLE_AUTHOR]
        ROLE_ADMIN: [ROLE_BLOGGER]
