#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

ood_comment_management_list:
    path: /admin/comments
    defaults: { _controller: OodCommentBundle:Management:list}
    methods: ["GET"]
