#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

ood_comment_getComments_getComments:
    path: /comments/{threadId}
    defaults: { _controller: OodCommentBundle:GetComments:getComments}
    methods: ["GET"]

ood_comment_postComments_postComments:
    path: /postComments/article/{postId}
    defaults: { _controller: OodCommentBundle:PostComments:postComments}
    methods: ["GET","POST"]

ood_comment_management_list:
    path: /admin/comments
    defaults: { _controller: OodCommentBundle:Management:list}
    methods: ["GET"]

ood_comment_management_approve:
    path: /admin/comment/{commentId}/approve
    defaults: { _controller: OodCommentBundle:Management:approve}
    methods: ["GET"]

ood_comment_management_disapprove:
    path: /admin/comment/{commentId}/disapprove
    defaults: { _controller: OodCommentBundle:Management:disapprove}
    methods: ["GET"]

ood_comment_management_edit:
    path: /admin/comment/{commentId}/edit
    defaults: { _controller: OodCommentBundle:Management:edit}
    methods: ["GET","POST"]
