#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

## Frontend
##
ood_comment_threadComment_thread:
    path: /commentaires/{threadId}
    defaults: { _controller: OodCommentBundle:ThreadComment:thread}
    methods: ["GET","POST"]

ood_comment_threadComment_newComment:
    path: /ajouter-commentaire/{threadId}
    defaults: { _controller: OodCommentBundle:ThreadComment:newComment}
    methods: ["GET","POST"]

## Backend
##
ood_comment_management_list:
    path: /admin/commentaires
    defaults: { _controller: OodCommentBundle:Management:list}
    methods: ["GET"]

ood_comment_management_approve:
    path: /admin/commentaire/{commentId}/approuver
    defaults: { _controller: OodCommentBundle:Management:approve}
    methods: ["GET"]

ood_comment_management_disapprove:
    path: /admin/commenaire/{commentId}/desapprouver
    defaults: { _controller: OodCommentBundle:Management:disapprove}
    methods: ["GET"]

ood_comment_management_edit:
    path: /admin/commentaire/{commentId}/modifier
    defaults: { _controller: OodCommentBundle:Management:edit}
    methods: ["GET","POST"]
