#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

services:
#    ood_comment.example:
#        class: Ood\CommentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
