#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

services:
  ## Autowiring
    #
    Ood\CommentBundle\:
        resource: '%kernel.project_dir%/src/Ood/CommentBundle/*'
        autowire: true
        autoconfigure: true
    #
    Ood\CommentBundle\Controller\:
        resource: '%kernel.project_dir%/src/Ood/CommentBundle/Controller'
        tags: ['controller.service_arguments']
    #
    Ood\CommentBundle\Manager\:
        resource: '%kernel.project_dir%/src/Ood/CommentBundle/Manager/'
        autowire: true
        autoconfigure: true
        public: true
