#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

ood_blog_post_list:
    path:     /
    defaults: { _controller: OodBlogBundle:Post:list }
    methods: ['GET','POST']

ood_blog_post_category:
    path:     /groupe/{slug}
    defaults: { _controller: OodBlogBundle:Post:category }
    methods: ['GET','POST']

ood_blog_post_new:
    path:     /ajouter-figure
    defaults: { _controller: OodBlogBundle:Post:new }
    methods: ['GET','POST']

ood_blog_post_edit:
    path:     /modifier-figure/{postId}
    defaults: { _controller: OodBlogBundle:Post:edit }
    methods: ['GET','POST']

ood_blog_post_remove:
    path:     /supprimer-figure/{postId}
    defaults: { _controller: OodBlogBundle:Post:remove }
    methods: ['GET']

ood_blog_post_show:
    path:     /figure/{slug}
    defaults: { _controller: OodBlogBundle:Post:show }
    methods: ['GET']


ood_blog_category_list:
    path: /groupes
    defaults: { _controller: OodBlogBundle:Category:list }

ood_blog_category_new:
    path: /ajouter-groupe
    defaults: { _controller: OodBlogBundle:Category:new }

ood_blog_category_edit:
    path: /modifier-groupe/{slug}
    defaults: { _controller: OodBlogBundle:Category:edit }
