#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

services:
  ## Services
    #
    ood_blog.slugify:
        class: Ood\BlogBundle\Services\Sluggable
        public: true
  ## Listeners
    #
    ood_blog.headerListener:
        arguments:
            - '@ood_blog.slugify'
        class: Ood\BlogBundle\EventListener\Entity\HeaderListener
        tags:
            - { name: doctrine.orm.entity_listener }
        public: true
