#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

# Homepage
app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
