#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

# Security:: Login
ood_user_security_login:
  path: /login
  defaults: { _controller: OodUserBundle:Security:login }
  methods: ["GET","POST"]

# Security:: Logout
ood_user_security_logout:
  path: /logout
  methods: ["GET"]
