#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

## **************************
## Frontend
##

## Security
#
# Security:: Login
ood_user_security_login:
  path: /login
  defaults: { _controller: OodUserBundle:Security:login }
  methods: ["GET","POST"]

# Security:: Logout
ood_user_security_logout:
  path: /logout
  methods: ["GET"]

## Registration
#
# Registration:: Register
ood_user_registration_register:
  path: /inscription
  defaults: { _controller: OodUserBundle:Registration:register }
  methods: ["GET","POST"]

# Registration : Check email
ood_user_registration_check_email:
  path: /inscription/consulter-messagerie
  defaults: { _controller: OodUserBundle:Registration:checkEmail}
  methods: ["GET"]

# Registration : confirm
ood_user_registration_confirm:
  path: /inscription/confirmer/{token}
  defaults: { _controller: OodUserBundle:Registration:confirm }

# Registration : confirmed
ood_user_registration_confirmed:
  path: /inscription/valide
  defaults: { _controller: OodUserBundle:Registration:confirmed }

## Resetting
#
# Resetting:: Request
ood_user_resetting_request:
  path: /mot-de-passe-oublie
  defaults: { _controller: OodUserBundle:Resetting:request}
  methods: ["GET", "POST"]

# Resetting:: Send email
ood_user_resetting_send_email:
  path: /mot-de-passe-oublie/reinitialiser
  defaults: { _controller: OodUserBundle:Resetting:sendEmail}
  methods: ["GET"]

# Resetting:: Check Email
ood_user_resetting_check_email:
  path: /mot-de-passe-oublie/consulter-messagerie
  defaults: { _controller: OodUserBundle:Resetting:checkEmail}
  methods: ["GET"]

# Resetting:: Reset
ood_user_resetting_reset:
  path: /mot-de-passe-oublie/renseigner-nouveau/{token}
  defaults: { _controller: OodUserBundle:Resetting:reset}
  methods: ["GET","POST"]

## Profile
#
# Profile edit
ood_user_profile_edit:
  path: /mon-compte
  defaults: { _controller: OodUserBundle:Profile:edit }
  methods: ["GET","POST"]

## **************************
## Backeutilisateur

## Admin
#
# User:admin:list
ood_user_management_list:
  path: /admin/utilisateurs
  defaults: { _controller: OodUserBundle:Management:list }
  methods: ["GET"]

# User:admin:edit
ood_user_management_edit:
  path: /admin/utilisateur/{id}/modifier
  defaults: { _controller: OodUserBundle:Management:edit }
  methods: ["GET","POST"]

# User:admin:lock
ood_user_management_lock:
  path: /admin/utilisateur/{id}/verrouiller
  defaults: { _controller: OodUserBundle:Management:lock }
  methods: ["GET"]

# User:admin:unlock
ood_user_management_unlock:
  path: /admin/utilisateur/{id}/deverouiller
  defaults: { _controller: OodUserBundle:Management:unlock }
  methods: ["GET"]
