#/**
# * This file is part of oc_snowtricks project
# *
# * @author: Sébastien CHOMY <sebastien.chomy@gmail.com>
# * @since 2018/02
# */

## **************************
## Frontend
##

# Security:: Login
ood_user_security_login:
  path: /login
  defaults: { _controller: OodUserBundle:Security:login }
  methods: ["GET","POST"]

# Security:: Logout
ood_user_security_logout:
  path: /logout
  methods: ["GET"]

# Registration:: Register
ood_user_registration_register:
  path: /inscription
  defaults: { _controller: OodUserBundle:Registration:register }
  methods: ["GET","POST"]

## **************************
## Backend
##

# User:admin:list
ood_user_management_list:
  path: /admin/users
  defaults: { _controller: OodUserBundle:Management:list }
  methods: ["GET"]

# User:admin:edit
ood_user_management_edit:
  path: /admin/users/{id}/edit
  defaults: { _controller: OodUserBundle:Management:edit }
  methods: ["GET","POST"]

# User:admin:lock
ood_user_management_lock:
  path: /admin/users/{id}/lock
  defaults: { _controller: OodUserBundle:Management:lock }
  methods: ["GET"]

# User:admin:unlock
ood_user_management_unlock:
  path: /admin/users/{id}/unlock
  defaults: { _controller: OodUserBundle:Management:unlock }
  methods: ["GET"]
